version: '3.8'

services:
  ollama_service:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    restart: always
    ports:
      - "11435:11434"

  ollama_lient:
    build:
      context: ./ollamaModelClient
      dockerfile: Dockerfile
    depends_on:
      ollama_service:
        condition: service_started

  chainlit_service:
    restart: always
    ports:
      - "8000:8000"
    build:
      context: ./chainlit
      dockerfile: Dockerfile
    volumes:
      - ./chainlit/:/app
    depends_on:
      ollama_service:
        condition: service_started